"""JSON schemas for AST-Grep MCP Server data structures."""

import json
from typing import Dict, Any, Optional, List
from datetime import datetime
import jsonschema
from jsonschema import validate, ValidationError

# Call Graph JSON Schema
CALL_GRAPH_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/AndEnd-Collective/ast-mcp/blob/main/schemas/call-graph.json",
    "title": "Call Graph Schema",
    "description": "Schema for call graph data structure generated by AST-Grep MCP Server",
    "type": "object",
    "required": ["metadata", "nodes", "edges", "metrics", "statistics"],
    "properties": {
        "metadata": {
            "type": "object",
            "description": "Call graph generation metadata",
            "required": [
                "generation_time",
                "total_functions", 
                "total_calls",
                "filtered_functions",
                "filtered_calls",
                "total_edges"
            ],
            "properties": {
                "generation_time": {
                    "type": "string",
                    "format": "date-time",
                    "description": "ISO 8601 timestamp of call graph generation"
                },
                "total_functions": {
                    "type": "integer",
                    "minimum": 0,
                    "description": "Total number of functions detected"
                },
                "total_calls": {
                    "type": "integer", 
                    "minimum": 0,
                    "description": "Total number of function calls detected"
                },
                "filtered_functions": {
                    "type": "integer",
                    "minimum": 0,
                    "description": "Number of functions included in the graph after filtering"
                },
                "filtered_calls": {
                    "type": "integer",
                    "minimum": 0, 
                    "description": "Number of calls included in the graph after filtering"
                },
                "total_edges": {
                    "type": "integer",
                    "minimum": 0,
                    "description": "Total number of call relationship edges"
                },
                "filter_patterns": {
                    "type": "array",
                    "description": "Patterns used to filter functions",
                    "items": {"type": "string"}
                },
                "include_builtin_calls": {
                    "type": "boolean", 
                    "description": "Whether builtin calls were included"
                },
                "include_external_calls": {
                    "type": "boolean",
                    "description": "Whether external calls were included"
                },
                "max_depth": {
                    "type": "integer",
                    "description": "Maximum call depth analyzed"
                }
            },
            "additionalProperties": True
        },
        
        "nodes": {
            "type": "array",
            "description": "Array of function nodes in the call graph",
            "items": {
                "type": "object",
                "required": ["id", "type", "name", "language"],
                "properties": {
                    "id": {"type": "string"},
                    "type": {"type": "string", "enum": ["function"]},
                    "name": {"type": "string"},
                    "language": {"type": "string"},
                    "line_number": {"type": "integer", "minimum": 1}
                }
            }
        },
        
        "edges": {
            "type": "array", 
            "description": "Array of call relationship edges",
            "items": {
                "type": "object",
                "required": ["id", "source", "target", "type"],
                "properties": {
                    "id": {"type": "string"},
                    "source": {"type": ["string", "null"]},
                    "target": {"type": "string"},
                    "type": {"type": "string", "enum": ["calls"]},
                    "confidence": {"type": "number", "minimum": 0, "maximum": 1}
                }
            }
        },
        
        "metrics": {
            "type": "object",
            "description": "Call graph analysis metrics",
            "required": [
                "total_nodes",
                "total_edges", 
                "average_out_degree",
                "average_in_degree"
            ],
            "properties": {
                "total_nodes": {"type": "integer", "minimum": 0},
                "total_edges": {"type": "integer", "minimum": 0},
                "average_out_degree": {"type": "number", "minimum": 0},
                "average_in_degree": {"type": "number", "minimum": 0},
                "max_out_degree": {"type": "integer", "minimum": 0},
                "max_in_degree": {"type": "integer", "minimum": 0},
                "isolated_nodes": {"type": "integer", "minimum": 0}
            },
            "additionalProperties": True
        },
        
        "statistics": {
            "type": "object",
            "description": "Statistical analysis of the call graph",
            "required": [
                "functions_by_language",
                "calls_by_type"
            ],
            "properties": {
                "functions_by_language": {"type": "object"},
                "calls_by_type": {"type": "object"},
                "complexity_distribution": {"type": "object"},
                "file_dependencies": {"type": "object"}
            },
            "additionalProperties": True
        },
        
        "errors": {
            "type": "array",
            "description": "Errors encountered during call graph generation",
            "items": {
                "type": "object",
                "required": ["error"],
                "properties": {
                    "error": {"type": "string"}
                }
            }
        }
    },
    "additionalProperties": False
}


class CallGraphValidator:
    """Validator for call graph JSON data structures."""
    
    def __init__(self):
        """Initialize the validator with the call graph schema."""
        self.schema = CALL_GRAPH_SCHEMA
        
    def validate_call_graph(self, call_graph_data: Dict[str, Any]) -> Dict[str, Any]:
        """Validate call graph data against the JSON schema."""
        try:
            validate(instance=call_graph_data, schema=self.schema)
            return {
                'valid': True,
                'errors': [],
                'message': 'Call graph data is valid'
            }
        except ValidationError as e:
            return {
                'valid': False,
                'errors': [{'message': e.message, 'path': list(e.absolute_path)}],
                'message': f'Call graph validation failed: {e.message}'
            }
        except Exception as e:
            return {
                'valid': False,
                'errors': [{'message': str(e), 'path': []}],
                'message': f'Validation error: {str(e)}'
            }
    

def create_call_graph_validator() -> CallGraphValidator:
    """Create a new call graph validator instance."""
    return CallGraphValidator()


def validate_call_graph_data(data: Dict[str, Any]) -> Dict[str, Any]:
    """Convenience function to validate call graph data."""
    validator = create_call_graph_validator()
    return validator.validate_call_graph(data)


def get_call_graph_schema() -> Dict[str, Any]:
    """Get the call graph JSON schema."""
    return CALL_GRAPH_SCHEMA.copy()


def export_schema_to_file(file_path: str) -> bool:
    """Export the call graph schema to a JSON file."""
    try:
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(CALL_GRAPH_SCHEMA, f, indent=2, ensure_ascii=False)
        return True
    except Exception:
        return False
